name: Reusable Workflow

on:
  push:
    branches:
      - main 

jobs:
  Auto_WF:
    uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main
    with:
      var: ${{ inputs.var }}
      req: ${{ inputs.req }}
    secrets:
      pass: ${{ secrets.pass }}
      req: ${{ secrets.req }}

  Manual_WF:
    uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main
    with:
      var: ${{ inputs.var }}
      req: ${{ inputs.req }}
      environment: ${{  github.ref_name == 'main' && 'Approval' || null }}
    secrets:
      pass: ${{ secrets.pass }}
      req: ${{ secrets.req }}