name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  use-variable:
    runs-on: ubuntu-latest
    needs: workflow-A 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use variable from Workflow A
        run: |
          echo "The variable from Workflow A is: ${{ needs.workflow-A.outputs.my_var }}"

