name: Workflow B

on:
  workflow_call:
    inputs:
      var:
        description: 'A regular input'
        required: true
        type: string
      req:
        description: 'Required input'
        required: true
        type: string
      environment:
        required: false
        type: string

    secrets:
      pass:
        required: true
      req:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "This is a reusable workflow"
