name: 2nd Main Workflow

on:
  push:
    branches: ["Main"]

jobs:
  Printing_a_message:
    name: Printing a message
    runs-on: ubuntu-latest
    steps:
      - name: Printing a simple message  
        run:
          echo "This is Workflow-B"