name: Call a reusable workflow
on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: faraz9993/gitnet2/.github/workflows/workflow-A.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: faraz9993/gitnet2/.github/workflows/workflow-A.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
