name: Dev Workflow

on:
  push:
    branches: ["main"]

jobs:
  push_to_nexus:
    name: Push to Nexus
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Approval' || null }}
    steps:
      - name: Printing a simple message 
        run:
          echo "Hello World"