name: Reusable Workflow with Inputs and Secrets

on:
  workflow_call:
    inputs:
      var:
        description: 'A regular input'
        required: true
        type: string
      req:
        description: 'Required input'
        required: true
        type: string
    secrets:
      pass:
        required: true
      req:
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs and secrets
        run: |
          echo "Received input var: ${{ inputs.var }}"
          echo "Received input req: ${{ inputs.req }}"
          echo "Received secret pass: ${{ secrets.pass }}"
          echo "Received secret req: ${{ secrets.req }}"
