name: Reusable Workflow

on:
  push:
    branches:
      - main 
  workflow_call:
    inputs:
      var:
        description: 'A regular input'
        required: true
        type: string
      req:
        description: 'Required input'
        required: true
        type: string
    secrets:
      pass:
        required: true
      req:
        required: true

jobs:
  Auto_WF:
    uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main
    with:
      var: ${{ inputs.var }}
      req: ${{ inputs.req }}
    secrets:
      pass: ${{ secrets.pass }}
      req: ${{ secrets.req }}

  # Manual_WF:
  #   uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main
  #   environment:
  #     name: Approval
  #   with:
  #     var: ${{ inputs.var }}
  #     req: ${{ inputs.req }}
  #   secrets:
  #     pass: ${{ secrets.pass }}
  #     req: ${{ secrets.req }}
  manual-approval:
    name: Manual Approval
    uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main    
    permissions:
      issues: write
    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GIHTUB_TOKEN }}
          approvers: faraz9993
          minimum-approvals: 1
          issue-title: "Manual Approval Required"
          issue-body: "Please approve or deny the deployment."
