name: 2nd Workflow

on:
  push:
    branches: ["main"]

jobs:
  Printing_third_message:
    runs-on: ubuntu-latest
    steps:
      - name: Printing a simple message   
        run:
          echo "This is Workflow-B"