name: Main Workflow

on:
  push:
    branches: ["main"]

jobs:
  Printing_a_message:
    name: Printing a message
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Approval' || null }}
    steps:
      - name: Printing a simple message 
        run:
          echo "Hello World"