name: Reusable Workflow

on:
  push:
    branches:
      - main 
  workflow_call:
    inputs:
      var:
        description: 'A regular input'
        required: true
        type: string
      req:
        description: 'Required input'
        required: true
        type: string
    secrets:
      pass:
        required: true
      req:
        required: true

jobs:
  Print_first_message:
    uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main

  Print_second_message:
    uses: faraz9993/gitnet2/.github/workflows/workflow-B.yml@main
    environment: ${{ github.ref_name == 'main' && 'Approval' || null }}
 
