name: Example Workflow with 'with' and 'secrets'
on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run with both 'with' and 'secrets'
        uses: faraz9993/gitnet2/.github/workflows/workflow-A.yml@main
        with:
          config-path: .github/labeler.yml
          additional-param: some-value
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
          another-secret: ${{ secrets.MY_SECRET_KEY }}
