name: Reusable Workflow with Inputs and Secrets

on:
  push:
    branches:
      - main 
  workflow_call:
    inputs:
      var:
        description: 'A regular input'
        required: true
        type: string
      req:
        description: 'Required input'
        required: true
        type: string
    secrets:
      pass:
        required: true
      req:
        required: true

jobs:
  Print_first_message:
    runs-on: ubuntu-latest
    steps:
      - name: Job-1
        run: echo "This is a Job-1"
  Print_second_message:
    uses: faraz9993/gitnet2/.github/workflows/workflow-A.yml@v1
    environment: ${{ github.ref_name == 'main' && 'Approval' || null }}
    with:
      var: ${{ inputs.var }}
      req: ${{ inputs.req }}  
    secrets:
      pass: ${{ secrets.pass }}
      req: ${{ secrets.req }}
