name: Workflow A

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'A custom input value'
        required: true
        type: string
        
jobs:
  generate-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use input variable
        id: use_input
        run: |
          echo "The input value is: ${{ github.event.inputs.my_input }}"

      - name: Set output variable
        id: set_output
        run: echo "::set-output name=my_var::${{ github.event.inputs.my_input }}"

    outputs:
      my_var: ${{ steps.set_output.outputs.my_var }}
